import Head from "next/head";
import { NextSeo } from "next-seo";
// import Image from "next/image";
import styles from "/styles/Home.module.css";
import MainPageContainer from "../src/components/units/mainPage/MainPage.index";
import LandingPage from "./landingPage";

export default function Home() {
  return (
    <>
      <NextSeo
        title="home"
        description="home description"
        canonical="https://example.com"
        openGraph={{
          url: "https://example.com",
        }}
      />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <MainPageContainer /> */}
        <LandingPage />
        {/* <div className={styles.description}>
          <p>
            3팀 프론트엔드. &nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div> */}
      </main>
    </>
  );
}
