import Head from "next/head";
import { NextSeo } from "next-seo";
import LandingPage from "./landingPage";

export default function Home(): JSX.Element {
  return (
    <>
      <NextSeo
        title="holidays"
        description="holidays 원데이클래스 예약 사이트"
        canonical="https://example.com"
        openGraph={{
          url: "https://example.com",
        }}
      />
      <Head>
        <title>Holidays</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LandingPage />
      </main>
    </>
  );
}
